version: "3"

volumes:
  mongo_data: {}

networks:
  app-network:
    driver: bridge

services:
  backend:
    restart: always
    container_name: expressjs-rest-template_node_local
    build:
      context: .
      dockerfile: compose/node/Dockerfile_dev
    # command: nodemon --inspect=0.0.0.0:9229 --nolazy app.js
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ./backend:/home/app/expressjs-rest-template
      - /home/app/expressjs-rest-template/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:4.2
    container_name: expressjs-rest-template_mongo_local
    env_file:
      - .env
    command: mongod --port 27017 --storageEngine wiredTiger
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:5.0.12-alpine
    container_name: expressjs-rest-template_redis_local
    networks:
      - app-network

