version: "3"

volumes:
  mongo_data: {}
  mongo_backup: {}
  node_logs: {}
  media_data: {}

networks:
  app-network:
    driver: bridge

services:
  backend:
    restart: always
    container_name: react_news_backend_node_stage
    build:
      context: .
      dockerfile: compose/node/Dockerfile
    env_file:
      - .env
    volumes:
      - /home/app/react_news_backend/node_modules
      - node_logs:/home/app/react_news_backend/logs
      - media_data:/home/app/react_news_backend/uploads
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
    # tty: true
    
  mongo:
    restart: always
    image: mongo:4.2
    container_name: react_news_backend_mongo_stage
    env_file:
      - .env
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
    networks:
      - app-network

  redis:
    image: redis:5.0.12-alpine
    container_name: react_news_backend_redis_local
    networks:
      - app-network

  nginx:
    restart: always
    build: ./compose/nginx
    container_name: react_news_backend_nginx_stage
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

