version: "3"

volumes:
  mongo_data:
  mongo_backup:
  node_logs:
  media_data:

networks:
  app-network:
    driver: bridge

services:
  backend:
    restart: always
    container_name: expressjs-rest-template_node_prod
    build:
      context: .
      dockerfile: compose/node/Dockerfile
    env_file:
      - .env
    volumes:
      - /home/app/expressjs-rest-template/node_modules
      - node_logs:/home/app/expressjs-rest-template/logs
      - media_data:/home/app/expressjs-rest-template/uploads
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

    # tty: true
  mongo:
    restart: always
    image: mongo:4.2
    container_name: expressjs-rest-template_mongo_prod
    env_file:
      - .env
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
    networks:
      - app-network

  redis:
    image: redis:5.0.12-alpine
    container_name: expressjs-rest-template_redis_local
    networks:
      - app-network

  nginx:
    restart: always
    build: ./compose/nginx
    container_name: expressjs-rest-template_nginx_prod
    depends_on:
      -  backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

