FROM node:18.1.0-alpine

RUN addgroup -S app && adduser -S app -G app

ENV HOME=/home/app

COPY backend/package*.json $HOME/react_news_backend/
RUN mkdir $HOME/react_news_backend/logs
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/react_news_backend
RUN npm install

CMD ["npm", "start"]
